build-job:
  stage: build
  script:
    - ./build.sh

test-job:
  stage: test
  needs: ["build-job"]
  dependencies:
    - build-job
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e build/
  script:
    - cd ./gimbalsaurus
    - xcodebuild test -scheme gimbalsaurusTests
